SnmpWebApp/Models/DeviceViewModel.cs
namespace SnmpWebApp.Models
{
    public class DeviceViewModel
    {
        public string IP { get; set; }
        public string OID { get; set; }
        public string DeviceName { get; set; }
        public string Username { get; set; }
        public string UpTime { get; set; }
        public string SysDescription { get; set; }
        public string Result { get; set; }
        public Guid Id { get; set; } = Guid.NewGuid(); 
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime Date { get; set; } = DateTime.Now;
        public string newValue { get; set; }
    }
}

SnmpWebApp/Models/ErrorViewModel.cs
namespace SnmpWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SnmpWebApp/Controllers/DataBaseController.cs
using Microsoft.AspNetCore.Mvc;
using SnmpWebApp.Service;

namespace SnmpWebApp.Controllers
{
    public class DataBaseController : Controller
    {
        private readonly DataBaseService _dataBaseService;

        public DataBaseController()
        {
            _dataBaseService = new DataBaseService();
        }
        [HttpGet]
        public IActionResult listItens()
        {
            var itens = _dataBaseService.ListItensInDataBase();
           return View(itens);
        }

    }
}

SnmpWebApp/Controllers/DeviceController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SnmpWebApp.Models;
using SnmpWebApp.Service;

namespace SnmpWebApp.Controllers
{
    public class DeviceController : Controller
    {
        private readonly DeviceService _deviceService;
        private readonly DataBaseService _dataBaseService = new();

        public DeviceController(DeviceService deviceService)
        {
            _deviceService = deviceService;
        }

        [HttpGet]
        public IActionResult ListItens()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SetDevice()
        {
            DeviceViewModel model = new DeviceViewModel();
            return View(model);
        }

        [HttpGet]
        public IActionResult GetDevice(string oid = "")
        {
            var model = new DeviceViewModel
            {
                OID = oid
            };

            return View(model);
        }
        [HttpGet]
        public IActionResult WalkDevice()
        {
            return View(new DeviceViewModel());
        }
        [HttpGet]
        public IActionResult SnmpInfo()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SetDevice(DeviceViewModel model)
        {
            try
            {
                model.Result = await _deviceService.SetDeviceByIpAsync(model.IP, model.OID, model.newValue);
            }
            catch
            {
                model.Result = $"Ao tentar fazer um Set na oid {model.OID}, retornou Erro.";
            }

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> GetDevice(DeviceViewModel model, string action)
        {
            try
            {

                if (action == "consult")
                {
                    model.Result = await _deviceService.GetDeviceByIpAsync(model.IP, model.OID);
                }
                else if (action == "saveOnDataBase")
                {
                    var result = await _deviceService.GetDeviceByIpAsync(model.IP, model.OID);
                    model.Result = _dataBaseService.SaveResulInLiteDb(model, result);
                }
            }
            catch
            {
                model.Result = $"Ao tentar fazer um GET na oid {model.OID}, retornou Erro.";
            }

            return View(model);

        }
        public async Task<IActionResult> WalkDevice(DeviceViewModel model)
        {
            var jsonResponse = await _deviceService.GetStaticsInfos(model.IP);

            var deviceInfo = JsonConvert.DeserializeObject<DeviceViewModel>(jsonResponse);

            return View(new DeviceViewModel
            {
                DeviceName = deviceInfo.DeviceName,
                Username = deviceInfo.Username,
                UpTime = deviceInfo.UpTime,
                SysDescription = deviceInfo.SysDescription
            });
        }
    }
}

SnmpWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SnmpWebApp.Models;
using System.Diagnostics;

namespace SnmpWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SnmpWebApp/Views/DataBase/ListItens.cshtml
@{
    ViewData["Title"] = "View";
}

@model List<DeviceViewModel>

<h2>Lista de Dispositivos</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>OID</th>
            <th>Descrição</th>
            <th>Data</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var device in Model)
        {
            <tr>
                <td>@device.Id</td>
                <td>@device.OID</td>
                <td>@device.Result</td>
                <td>@device.Date.ToString("dd/MM/yyyy HH:mm")</td>
            </tr>
        }
    </tbody>
</table>

SnmpWebApp/Views/Device/GetDevice.cshtml
@model SnmpWebApp.Models.DeviceViewModel

@{
    ViewData["Title"] = "Consultar Dispositivo";
}

<h2>Consultar Dispositivo SNMP</h2>

<form asp-action="GetDevice" method="post">
    <div>
        <label for="Ip">IP:</label>
        <input type="text" id="Ip" name="Ip" required />
    </div>
    <div>
        <label for="OID">OID:</label>
        <input type="text" id="OID" name="OID" value="@Model.OID" required />
    </div>
    <div>
        <button type="submit" name="action" value="consult">Consultar</button>
        <button type="submit" name="action" value="saveOnDataBase">Consultar e Gravar no banco</button>
    </div>
</form>


@if (Model?.Result != null)
{
    <div>
        <h3>Resultado:</h3>
        <p>@Model.Result</p>
    </div>
}

SnmpWebApp/Views/Device/SetDevice.cshtml
@model SnmpWebApp.Models.DeviceViewModel

@{
    ViewData["Title"] = "Consultar Dispositivo";
}

<h2>Setar valor via SNMP</h2>

<form asp-action="SetDevice" method="post">
    <div>
        <label for="Ip">IP:</label>
        <input type="text" id="Ip" name="Ip" required />
    </div>
    <div>
        <label for="OID">OID:</label>
        <input type="text" id="OID" name="OID" value="@Model.OID" required />
    </div>
    <div>
        <label for="newValue">Valor para ser Setado:</label>
        <input type="text" id="newValue" name="newValue" value="@Model.newValue" required />
    </div>
    <div>
        <button type="submit">Setar valor</button>
    </div>
</form>


@if (Model?.Result != null)
{
    <div>
        <h3>Resultado:</h3>
        <p>@Model.Result</p>
    </div>
}

SnmpWebApp/Views/Device/SnmpInfo.cshtml
@using Microsoft.AspNetCore.Html
@model SnmpWebApp.Models.DeviceViewModel

@{
    ViewData["Title"] = "Informações sobre SNMP";
}

<h2>Lista de Oids para informações</h2>

<form asp-action="SnmpInfo" method="dialog">

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Valor Oid</th>
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.1.5.0", "Device Name")
                </td>
                <td>1.3.6.1.2.1.1.5.0</td>
                <td>Nome do dispositivo SNMP</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.77.1.2.25", "User Name")
                </td>
                <td>1.3.6.1.4.1.77.1.2.25</td>
                <td>Usuário para autenticação</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.1.3.0", "UpTime")
                </td>
                <td>1.3.6.1.2.1.1.3.0</td>
                <td>Tempo de atividade do dispositivo</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.1.1.0", "System Descryption")
                </td>
                <td>1.3.6.1.2.1.1.1.0</td>
                <td>Descrição do sistema SNMP</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.1.4.0", "System Contact")
                </td>
                <td>1.3.6.1.2.1.1.4.0</td>
                <td>Informações de contato do administrador</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.1.6.0", "System Location")
                </td>
                <td>1.3.6.1.2.1.1.6.0</td>
                <td>Localização do dispositivo</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.4.20", "Ip Address Table")
                </td>
                <td>1.3.6.1.2.1.4.20</td>
                <td>Tabela de endereços IP do dispositivo</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.2.2.1.6", "Mac Address")
                </td>
                <td>1.3.6.1.2.1.2.2.1.6</td>
                <td>Endereço MAC da interface de rede</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.1.5.0", "Hostname")
                </td>
                <td>1.3.6.1.2.1.1.5.0</td>
                <td>Nome do host do dispositivo</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.2021.11.10.0", "CPU Load")
                </td>
                <td>1.3.6.1.4.1.2021.11.10.0</td>
                <td>Carga atual da CPU</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.2021.4.5.0", "Total Memory")
                </td>
                <td>1.3.6.1.4.1.2021.4.5.0</td>
                <td>Quantidade total de memória RAM</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.2021.4.6.0", "Avaliable Memory")
                </td>
                <td>1.3.6.1.4.1.2021.4.6.0</td>
                <td>Memória RAM disponível</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.25.2.3.1.5", "Disk Storage")
                </td>
                <td>1.3.6.1.2.1.25.2.3.1.5</td>
                <td>Capacidade total de armazenamento do disco</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.2021.9.1.7", "Free Disk Space")
                </td>
                <td>1.3.6.1.4.1.2021.9.1.7</td>
                <td>Espaço livre em disco</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.25.1.6.0", "Process count")
                </td>
                <td>1.3.6.1.2.1.25.1.6.0</td>
                <td>Número total de processos em execução</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.77.1.2.25", "System users")
                </td>
                <td>1.3.6.1.4.1.77.1.2.25</td>
                <td>Usuários conectados ao sistema</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.2.2.1", "Network Interface List")
                </td>
                <td>1.3.6.1.2.1.2.2.1</td>
                <td>Lista de interfaces de rede disponíveis</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.2.2.1.5", "Network Interface Speed")
                </td>
                <td>1.3.6.1.2.1.2.2.1.5</td>
                <td>Velocidade de uma interface de rede específica</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.2.2.1.10", "Inbound Network Traffic")
                </td>
                <td>1.3.6.1.2.1.2.2.1.10</td>
                <td>Tráfego de entrada na interface de rede</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.2.2.1.16", "Outbound Network Traffic")
                </td>
                <td>1.3.6.1.2.1.2.2.1.16</td>
                <td>Tráfego de saída na interface de rede</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.2.2.1.14", "Error Packets Inbound")
                </td>
                <td>1.3.6.1.2.1.2.2.1.14</td>
                <td>Pacotes com erro recebidos na interface de rede</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.2.2.1.20", "Error Packets Outbound")
                </td>
                <td>1.3.6.1.2.1.2.2.1.20</td>
                <td>Pacotes com erro enviados pela interface de rede</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.25.4.2.1.2", "Running SoftwareTable")
                </td>
                <td>1.3.6.1.2.1.25.4.2.1.2</td>
                <td>Lista de softwares em execução no sistema</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.25.6.3.1.2", "Installed Software Table")
                </td>
                <td>1.3.6.1.2.1.25.6.3.1.2</td>
                <td>Lista de softwares instalados no sistema</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.2.1.25.3.3.1.2", "Processor Load")
                </td>
                <td>1.3.6.1.2.1.25.3.3.1.2</td>
                <td>Carga do processador (por núcleo)</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.2021.4.11.0", "Physical Memory Used")
                </td>
                <td>1.3.6.1.4.1.2021.4.11.0</td>
                <td>Quantidade de memória física em uso</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.2021.4.15.0", "Virtual Memory Used")
                </td>
                <td>1.3.6.1.4.1.2021.4.15.0</td>
                <td>Quantidade de memória virtual em uso</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.2021.4.3.0", "Swap Space Total")
                </td>
                <td>1.3.6.1.4.1.2021.4.3.0</td>
                <td>Total de espaço de swap disponível</td>
            </tr>
            <tr>
                <td>
                    @GenerateOidLink("1.3.6.1.4.1.2021.4.4.0", "Swap Space avalable")
                </td>
                <td>1.3.6.1.4.1.2021.4.4.0</td>
                <td>Espaço de swap disponível</td>
            </tr>
        </tbody>
    </table>

    </tbody>
    </table>
</form>

@functions {
    public IHtmlContent GenerateOidLink(string oid, string nome)
    {
        return new HtmlString($"<a href='{Url.Action("GetDevice", "Device", new { oid = oid })}'>{nome}</a>");
    }
}

SnmpWebApp/Views/Device/WalkDevice.cshtml
@model SnmpWebApp.Models.DeviceViewModel

@{
    ViewData["Title"] = "Consultar Informações no Dispositivo";
}

<h2>Consultar Dispositivo SNMP</h2>

<form asp-action="WalkDevice" method="post">
    <div>
        <label for="Ip">IP:</label>
        <input type="text" id="Ip" name="Ip" required />
    </div>
    <button type="submit">Consultar</button>
</form>

@if (Model != null)
{
    <div>
        <h3>Resultado:</h3>
        <dl>
            <dt>Device Name:</dt>
            <dd>@Model.DeviceName</dd>

            <dt>Username:</dt>
            <dd>@Model.Username</dd>

            <dt>Up Time:</dt>
            <dd>@Model.UpTime</dd>

            <dt>System Description:</dt>
            <dd>@Model.SysDescription</dd>
        </dl>
    </div>
}

SnmpWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="div-GetDevice">
    <br />
    <p>Pressione o botão abaixo para consultar um dispositivo.</p>
    <button class="btn btn-primary" onclick="window.location.href='/Device/GetDevice'">Consultar Dispositivo</button>

</div>
<div class="div-SetDevice">
    <br />
    <p>Ver itens que estão salvos</p>
    <button class="btn btn-primary" onclick="window.location.href='/Device/SetDevice'">Setar informação</button>
</div>
<div class="div-WalkDevice">
    <br />
    <p>Pressione o botão abaixo para consultar informações em um dispositivo.</p>
    <button class="btn btn-primary" onclick="window.location.href='/Device/WalkDevice'">Consultar Informações Dispositivo</button>
</div>
<div class="div-ListSnmp">
    <br />
    <p>Está com dúvidas referente oque pode monitorar?</p>
    <button class="btn btn-primary" onclick="window.location.href='/Device/SnmpInfo'">Preciso de ajuda</button>
</div>
<div class="div-ListDataBaseItens">
    <br />
    <p>Ver itens que estão salvos</p>
    <button class="btn btn-primary" onclick="window.location.href='/DataBase/ListItens'">Visualizar</button>
</div>

SnmpWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SnmpWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SnmpWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SnmpWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SnmpWebApp</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>